import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";
import i18n from "../../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_InsurancePremiums",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_InsurancePremiums",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_InsurancePremiumsNotPayrollTax",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_InsurancePremiumsNotPayrollTax",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_LongTermCareInsurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_LongTermCareInsurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_AnyXpecialNeedsServices",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_AnyXpecialNeedsServices",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_PrescriptionDrugsAndMedicalSupplies",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_PrescriptionDrugsAndMedicalSupplies",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_TransportationServices",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_TransportationServices",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: false,
    question: "taxPayer_MedicalExpenses_Rentals",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.medicalExpenses,
    forSpouse: true,
    question: "spouse_MedicalExpenses_Rentals",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.deductions.step1.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.deductions.step1.no"),
    value: false,
  },
];

export const DATA_AMOUNT_PAID = [
  {
    label: "INSURANCE PREMIUMS for Medical, Dental, Vision & Hospital ",
    value: 0,
  },
  {
    label: "Medicare Insurance Premiums (Not payroll tax)",
    value: 1,
  },
  {
    label: "Long-Term Care Insurance",
    value: 2,
  },
  {
    label:
      "Hospitals, Doctors, Dentists,  Chiropractors, eye exams, therapy and special needs services and other medical professionals and co payments",
    value: 3,
  },
  {
    label: "Prescription Drugs, medical supplies, including PPE. ",
    value: 4,
  },
  {
    label:
      "Transportation services, air fare and lodging  (for medical treatment) to and from treatment centers.",
    value: 5,
  },
  {
    label:
      "Rentals (crutches, wheelchair, walker, oxygen equipment, medical required home improvements and placards for the Disabled.etc.)",
    value: 6,
  },
];

export const DATA_KEY = [
  "taxPayer_MedicalExpenses",
  "spouse_MedicalExpenses",
  "taxPayer_MedicalExpenses_InsurancePremiums",
  "spouse_MedicalExpenses_InsurancePremiums",
  "taxPayer_MedicalExpenses_InsurancePremiumsNotPayrollTax",
  "spouse_MedicalExpenses_InsurancePremiumsNotPayrollTax",
  "taxPayer_MedicalExpenses_LongTermCareInsurance",
  "spouse_MedicalExpenses_LongTermCareInsurance",
  "taxPayer_MedicalExpenses_AnyXpecialNeedsServices",
  "spouse_MedicalExpenses_AnyXpecialNeedsServices",
  "taxPayer_MedicalExpenses_PrescriptionDrugsAndMedicalSupplies",
  "spouse_MedicalExpenses_PrescriptionDrugsAndMedicalSupplies",
  "taxPayer_MedicalExpenses_TransportationServices",
  "spouse_MedicalExpenses_TransportationServices",
  "taxPayer_MedicalExpenses_Rentals",
  "spouse_MedicalExpenses_Rentals",
];
