import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";

export const taxPayer = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "do_you_use_accounting_software_prepare_income_tax",
    answerTypeId: QUESTION_TYPE_ANSWER.radio,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "do_you_use_accounting_software_prepare_income_tax_attachment",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessName1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_EmployerIDNumber1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_productOrService1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_SelfEmployedHealthInsuranceCost1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_GrossIncome1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_ReturnsAndAllowances1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_BeginningInventory1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_AdditionsToInventory1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusiness_EndingInventory1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Advertising1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_CommissionsandFees1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_ContractLabor1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_DuesAndPublications1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Meals1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_EmployeeBenefitPrograms1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_EmployeeHealthBenefitPlans1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Equipment1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Freight1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Gifts1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_InsuranceNotHealth1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_InterestMortgage1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_InterestOther1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_BusinessInternetService1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_LeaseImprovements1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_LegalProfessional1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Licenses1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_OfficeExpense1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_PensionPlanFees1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_RentEquipment1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_RentOther1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Repairs1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Supplies1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_TaxesPayroll1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_TaxesSales1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_TaxesProperty1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_BusinessTelephone1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Utilities1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Wages1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerBusinessExpense_Other1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const spouse = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "spouse_do_you_use_accounting_software_prepare_income_tax",
    answerTypeId: QUESTION_TYPE_ANSWER.radio,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "spouse_do_you_use_accounting_software_prepare_income_tax_attachment",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },  
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessName1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_EmployerIDNumber1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_SelfEmployedHealthInsuranceCost1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_GrossIncome1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_ReturnsAndAllowances1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_BeginningInventory1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_AdditionsToInventory1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusiness_EndingInventory1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Advertising1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_CommissionsandFees1",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_ContractLabor1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_DuesAndPublications1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Meals1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_EmployeeBenefitPrograms1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_EmployeeHealthBenefitPlans1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Equipment1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Freight1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Gifts1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_InsuranceNotHealth1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_InterestMortgage1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_InterestOther1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_BusinessInternetService1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_LeaseImprovements1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_LegalProfessional1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Licenses1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_OfficeExpense1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_PensionPlanFees1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_RentEquipment1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_RentOther1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Repairs1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Supplies1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_TaxesPayroll1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_TaxesSales1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_TaxesProperty1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_BusinessTelephone1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Utilities1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Wages1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseBusinessExpense_Other1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const DATA_KEY = [
  "do_you_use_accounting_software_prepare_income_tax",
  "do_you_use_accounting_software_prepare_income_tax_attachment",
  "qualification_education_expense",
  "taxPayerBusinessName",
  "taxPayerBusiness_EmployerIDNumber",
  "taxPayerBusiness_SelfEmployedHealthInsuranceCost",
  "taxPayerBusiness_productOrService",
  "taxPayerBusiness_GrossIncome",
  "taxPayerBusiness_ReturnsAndAllowances",
  "taxPayerBusiness_BeginningInventory",
  "taxPayerBusiness_AdditionsToInventory",
  "taxPayerBusiness_EndingInventory",
  "taxPayerBusinessExpense_Advertising",
  "taxPayerBusinessExpense_CommissionsandFees",
  "taxPayerBusinessExpense_ContractLabor",
  "taxPayerBusinessExpense_DuesAndPublications",
  "taxPayerBusinessExpense_Meals",
  "taxPayerBusinessExpense_EmployeeBenefitPrograms",
  "taxPayerBusinessExpense_EmployeeHealthBenefitPlans",
  "taxPayerBusinessExpense_Equipment",
  "taxPayerBusinessExpense_Freight",
  "taxPayerBusinessExpense_Gifts",
  "taxPayerBusinessExpense_InsuranceNotHealth",
  "taxPayerBusinessExpense_InterestMortgage",
  "taxPayerBusinessExpense_InterestOther",
  "taxPayerBusinessExpense_BusinessInternetService",
  "taxPayerBusinessExpense_LeaseImprovements",
  "taxPayerBusinessExpense_LegalProfessional",
  "taxPayerBusinessExpense_Licenses",
  "taxPayerBusinessExpense_OfficeExpense",
  "taxPayerBusinessExpense_PensionPlanFees",
  "taxPayerBusinessExpense_RentEquipment",
  "taxPayerBusinessExpense_RentOther",
  "taxPayerBusinessExpense_Repairs",
  "taxPayerBusinessExpense_Supplies",
  "taxPayerBusinessExpense_TaxesPayroll",
  "taxPayerBusinessExpense_TaxesSales",
  "taxPayerBusinessExpense_TaxesProperty",
  "taxPayerBusinessExpense_BusinessTelephone",
  "taxPayerBusinessExpense_Utilities",
  "taxPayerBusinessExpense_Wages",
  "taxPayerBusinessExpense_Other",
  "spouse_do_you_use_accounting_software_prepare_income_tax",
  "spouse_do_you_use_accounting_software_prepare_income_tax_attachment",
  "spouseBusinessName",
  "spouseBusiness_EmployerIDNumber",
  "spouseBusiness_SelfEmployedHealthInsuranceCost",
  "spouseBusiness_GrossIncome",
  "spouseBusiness_ReturnsAndAllowances",
  "spouseBusiness_BeginningInventory",
  "spouseBusiness_AdditionsToInventory",
  "spouseBusiness_EndingInventory",
  "spouseBusinessExpense_Advertising",
  "spouseBusinessExpense_CommissionsandFees",
  "spouseBusinessExpense_ContractLabor",
  "spouseBusinessExpense_DuesAndPublications",
  "spouseBusinessExpense_Meals",
  "spouseBusinessExpense_EmployeeBenefitPrograms",
  "spouseBusinessExpense_EmployeeHealthBenefitPlans",
  "spouseBusinessExpense_Equipment",
  "spouseBusinessExpense_Freight",
  "spouseBusinessExpense_Gifts",
  "spouseBusinessExpense_InsuranceNotHealth",
  "spouseBusinessExpense_InterestMortgage",
  "spouseBusinessExpense_InterestOther",
  "spouseBusinessExpense_BusinessInternetService",
  "spouseBusinessExpense_LeaseImprovements",
  "spouseBusinessExpense_LegalProfessional",
  "spouseBusinessExpense_Licenses",
  "spouseBusinessExpense_OfficeExpense",
  "spouseBusinessExpense_PensionPlanFees",
  "spouseBusinessExpense_RentEquipment",
  "spouseBusinessExpense_RentOther",
  "spouseBusinessExpense_Repairs",
  "spouseBusinessExpense_Supplies",
  "spouseBusinessExpense_TaxesPayroll",
  "spouseBusinessExpense_TaxesSales",
  "spouseBusinessExpense_TaxesProperty",
  "spouseBusinessExpense_BusinessTelephone",
  "spouseBusinessExpense_Utilities",
  "spouseBusinessExpense_Wages",
  "spouseBusinessExpense_Other",
];
