import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../constants/organizer";
import i18n from "../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_NameOfBusiness",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_EmployerIdNumber",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_Street",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_City",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_ZipCode",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_State",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_FullName",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_Email",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.businessEntityTaxReturn,
    forSpouse: false,
    question: "businessEntity_Phone",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.deductions.step2.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.deductions.step2.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "businessEntity_NameOfBusiness",
  "businessEntity_EmployerIdNumber",
  "businessEntity_Street",
  "businessEntity_City",
  "businessEntity_ZipCode",
  "businessEntity_State",
  "businessEntity_FullName",
  "businessEntity_Email",
  "businessEntity_Phone",
];
