export const QUOTE_STATUS = {
  ACCEPTED: 6,
  NOT_ACCEPTED: 7,
  PENDING: 8,
};

export const JOB_STATUS = {
  NOT_STARTED: 1,
  IN_PROCESS: 2,
  IN_FOR_REVIEW: 3,
  FILLED: 4,
  WAITING_FOR_INFORMATION: 9,
};

export const ACTION_STATUS = {
  CHOSEN_WAITING_FOR_INFORMATION: 9,
  CONFIRMED: 10,
  DECLINED: 11,
};
