import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";
import i18n from "../../../../../i18n";

export const initialTaxPayerData = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_PayHomeMortgageinterest",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_Reseive1098Form",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_Form1098Upload",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_PayeeName",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_SecondHome",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_EquityLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_CheckIfHomeQualified",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_HasOriginalHomeLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_RefinanceAnyLoans",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_Name1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_SSN1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: false,
    question: "taxPayer_MortgageInterest_PaidTo_Address1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const initialSpouseData = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_PayHomeMortgageinterest",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_Reseive1098Form",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_PayeeName",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_SecondHome",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_EquityLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_CheckIfHomeQualified",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_HasOriginalHomeLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_RefinanceAnyLoans",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_Name1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_SSN1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeMortgageINterest,
    forSpouse: true,
    question: "spouse_MortgageInterest_PaidTo_Address1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.deductions.step1.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.deductions.step1.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "taxPayer_PayHomeMortgageinterest",
  "taxPayer_Reseive1098Form",
  "taxPayer_Form1098Upload",
  "taxPayer_MortgageInterest_PaidTo_PayeeName",
  "taxPayer_MortgageInterest_PaidTo_Amount",
  "taxPayer_MortgageInterest_PaidTo_SecondHome",
  "taxPayer_MortgageInterest_PaidTo_EquityLoan",
  "taxPayer_MortgageInterest_PaidTo_CheckIfHomeQualified",
  "taxPayer_MortgageInterest_HasOriginalHomeLoan",
  "taxPayer_MortgageInterest_PaidTo_RefinanceAnyLoans",
  "taxPayer_MortgageInterest_PaidTo_Name1",
  "taxPayer_MortgageInterest_PaidTo_SSN1",
  "taxPayer_MortgageInterest_PaidTo_Address1",
  "spouse_PayHomeMortgageinterest",
  "spouse_Reseive1098Form",
  "spouse_MortgageInterest_PaidTo_PayeeName",
  "spouse_MortgageInterest_PaidTo_Amount",
  "spouse_MortgageInterest_PaidTo_SecondHome",
  "spouse_MortgageInterest_PaidTo_EquityLoan",
  "spouse_MortgageInterest_PaidTo_CheckIfHomeQualified",
  "spouse_MortgageInterest_HasOriginalHomeLoan",
  "spouse_MortgageInterest_PaidTo_RefinanceAnyLoans",
  "spouse_MortgageInterest_PaidTo_Name1",
  "spouse_MortgageInterest_PaidTo_SSN1",
  "spouse_MortgageInterest_PaidTo_Address1",
];
