import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";

export const dataTaxpayerQuestion = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.w2Form,
    forSpouse: false,
    question: "taxPayer_W2FormFile",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.w2Form,
    forSpouse: false,
    question: "taxPayer_DoNotHaveMoreW2Form",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.w2Form,
    forSpouse: false,
    question: "taxPayer_HaveMoreRemindLater",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.w2Form,
    forSpouse: true,
    question: "spouse_W2FormFile",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.w2Form,
    forSpouse: true,
    question: "spouse_DoNotHaveMoreW2Form",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.w2Form,
    forSpouse: true,
    question: "spouse_HaveMoreRemindLater",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const DATA_KEY = [
  "taxPayer_W2FormFile",
  "taxPayer_DoNotHaveMoreW2Form",
  "taxPayer_HaveMoreRemindLater",
  "spouse_W2FormFile",
  "spouse_DoNotHaveMoreW2Form",
  "spouse_HaveMoreRemindLater",
];
