import i18n from "../../../../../i18n";
import { IRadioGroupItem } from "../../../../../components/RadioGroup/index.props";
import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";

export const taxPayer = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_1099INTOrDIVFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayerRealEstate_ProvideAny1099ks",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_1099BFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHave1099BFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_HaveVirtualOrCryptoCurrencyTransactions",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_1099RFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHave1099RFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotReceivedYet1099RFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_1099SSAFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHave1099SSAFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotReceivedYet1099SSAFormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_1099GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHave1099GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotReceivedYet1099GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_ScheduleK1FormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHaveScheduleK1FormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotReceivedYetScheduleK1FormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_1099SFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHave1099SFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotReceivedYet1099SFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_ReceiveAnyOtherTypeOfIncome",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_W2GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotHaveW2GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: false,
    question: "taxPayer_DoNotReceivedYetW2GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "taxPayer_HaveVirtualOrCryptoCurrencyTransactions_Document",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "taxPayer_ReceiveAnyOtherTypeOfIncome_Document",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
];

export const spouse = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_1099INTOrDIVFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouseRealEstate_ProvideAny1099ks",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_1099BFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHave1099BFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_HaveVirtualOrCryptoCurrencyTransactions",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_1099RFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHave1099RFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotReceivedYet1099RFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_1099SSAFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHave1099SSAFormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotReceivedYet1099SSAFormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_1099GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHave1099GFormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotReceivedYet1099GFormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_ScheduleK1FormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHaveScheduleK1FormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotReceivedYetScheduleK1FormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_1099SFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHave1099SFormDocument",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotReceivedYet1099SFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_ReceiveAnyOtherTypeOfIncome",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_W2GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotHaveW2GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_DoNotReceivedYetW2GFormDocument",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_ReceiveAnyOtherTypeOfIncome_Document",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.income,
    forSpouse: true,
    question: "spouse_HaveVirtualOrCryptoCurrencyTransactions_Document",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
];

export const radioButtons: IRadioGroupItem[] = [
  {
    label: i18n.t("organizer.individual.income.step6.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.individual.income.step6.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "taxPayer_1099INTOrDIVFormDocument",
  "taxPayerRealEstate_ProvideAny1099ks",
  "taxPayer_1099BFormDocument",
  "taxPayer_DoNotHave1099BFormDocument",
  "taxPayer_HaveVirtualOrCryptoCurrencyTransactions",
  "taxPayer_HaveVirtualOrCryptoCurrencyTransactions_Document",
  "taxPayer_ReceiveAnyOtherTypeOfIncome_Document",
  "taxPayer_1099RFormDocument",
  "taxPayer_DoNotHave1099RFormDocument",
  "taxPayer_DoNotReceivedYet1099RFormDocument",
  "taxPayer_1099SSAFormDocument",
  "taxPayer_DoNotHave1099SSAFormDocument",
  "taxPayer_DoNotReceivedYet1099SSAFormDocument",
  "taxPayer_1099GFormDocument",
  "taxPayer_DoNotHave1099GFormDocument",
  "taxPayer_DoNotReceivedYet1099GFormDocument",
  "taxPayer_ScheduleK1FormDocument",
  "taxPayer_DoNotHaveScheduleK1FormDocument",
  "taxPayer_DoNotReceivedYetScheduleK1FormDocument",
  "taxPayer_1099SFormDocument",
  "taxPayer_DoNotHave1099SFormDocument",
  "taxPayer_DoNotReceivedYet1099SFormDocument",
  "taxPayer_ReceiveAnyOtherTypeOfIncome",
  "taxPayer_W2GFormDocument",
  "taxPayer_DoNotHaveW2GFormDocument",
  "taxPayer_DoNotReceivedYetW2GFormDocument",
  "spouse_1099INTOrDIVFormDocument",
  "spouseRealEstate_ProvideAny1099ks",
  "spouse_1099BFormDocument",
  "spouse_HaveVirtualOrCryptoCurrencyTransactions_Document",
  "spouse_ReceiveAnyOtherTypeOfIncome_Document",
  "spouse_DoNotHave1099BFormDocument",
  "spouse_HaveVirtualOrCryptoCurrencyTransactions",
  "spouse_1099RFormDocument",
  "spouse_DoNotHave1099RFormDocument",
  "spouse_DoNotReceivedYet1099RFormDocument",
  "spouse_1099SSAFormDocument",
  "spouse_DoNotHave1099SSAFormDocument",
  "spouse_DoNotReceivedYet1099SSAFormDocument",
  "spouse_1099GFormDocument",
  "spouse_DoNotHave1099GFormDocument",
  "spouse_DoNotReceivedYet1099GFormDocument",
  "spouse_ScheduleK1FormDocument",
  "spouse_DoNotHaveScheduleK1FormDocument",
  "spouse_DoNotReceivedYetScheduleK1FormDocument",
  "spouse_1099SFormDocument",
  "spouse_DoNotHave1099SFormDocument",
  "spouse_DoNotReceivedYet1099SFormDocument",
  "spouse_ReceiveAnyOtherTypeOfIncome",
  "spouse_W2GFormDocument",
  "spouse_DoNotHaveW2GFormDocument",
  "spouse_DoNotReceivedYetW2GFormDocument",
];
