import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../constants/organizer";
import i18n from "../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_IsMamemberOfControlledGroupOfCorporations",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_IsPersonalHoldingCompany",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_IsQualifiedPersonalServiceCorporation",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question:
      "corporations_IsSubsidiaryInAffiliatedOrParentSubsidiaryControlledGroup",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question:
      "corporations_IsSubsidiaryInAffiliatedOrParentSubsidiaryControlledGroup_Details",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidAnyoneWwnDirectly20OrMore",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidThisCorporationOwnDirectly20OrMore",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_AreOfficersStockholdersPaidSalary",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidForeighPersonOwn25PersentOfTotalVotingPower",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_HasMadeAnyEstimatedTaxPayments",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidReceiveAnyDividendsFromAnotherCorporation",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidHaveTotalReceiptsOf500000OrMore",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "Corporations_DidPayDividends",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidPubliclyOfferedDebtInstruments",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidEarnAnyTaxExemptInterest",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DoesThisBusinessOwnAnyResidentialRentalBuildings",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DoesItHaveAnyBuiltInGainsOrEarnings",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidTheBusinessElectToDeferTheEmployers",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_WasTheOperationFullyOrPartiallyCurtailed",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question: "corporations_DidTheBusinessReceivePaycheckProtectionProgramLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToPartnerships,
    forSpouse: false,
    question:
      "corporations_DidTheBusinessReceivePaycheckProtectionProgramLoan_Details",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.business.step9.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.business.step9.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "corporations_IsMamemberOfControlledGroupOfCorporations",
  "corporations_IsPersonalHoldingCompany",
  "corporations_IsQualifiedPersonalServiceCorporation",
  "corporations_IsSubsidiaryInAffiliatedOrParentSubsidiaryControlledGroup",
  "corporations_IsSubsidiaryInAffiliatedOrParentSubsidiaryControlledGroup_Details",
  "corporations_DidAnyoneWwnDirectly20OrMore",
  "corporations_DidThisCorporationOwnDirectly20OrMore",
  "corporations_AreOfficersStockholdersPaidSalary",
  "corporations_DidForeighPersonOwn25PersentOfTotalVotingPower",
  "corporations_HasMadeAnyEstimatedTaxPayments",
  "corporations_DidReceiveAnyDividendsFromAnotherCorporation",
  "corporations_DidHaveTotalReceiptsOf500000OrMore",
  "Corporations_DidPayDividends",
  "corporations_DidPubliclyOfferedDebtInstruments",
  "corporations_DidEarnAnyTaxExemptInterest",
  "corporations_DoesThisBusinessOwnAnyResidentialRentalBuildings",
  "corporations_DoesItHaveAnyBuiltInGainsOrEarnings",
  "corporations_DidTheBusinessElectToDeferTheEmployers",
  "corporations_WasTheOperationFullyOrPartiallyCurtailed",
  "corporations_DidTheBusinessReceivePaycheckProtectionProgramLoan",
  "corporations_DidTheBusinessReceivePaycheckProtectionProgramLoan_Details",
];
