import i18n from "../../../../../i18n";
import { IRadioGroupItem } from "../../../../../components/RadioGroup/index.props";
import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";
import { ISelectProps } from "./index.props";

export const taxPayer = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Advertising",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_CleaningAndMaintenance",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Commissions",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Insurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Professional",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_LegalAndFees",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_ManagementFees",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_MortgageInterestPaidToBanks",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_OtherInterest",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Repairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_SuppliesHardwareEtc",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_TaxesProperty",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_TaxesPayroll",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Utilities",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_Wages",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_CondoOrHomeownerAssociationDues",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstateExpenses_ForShortTermRentals",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_OwnAnyMoreRealEstate",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_AddressOrDescription1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_Type1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_RentalIncome1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_PercentOwnership1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_IsVocationHome1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_NumberOfDaysPersonallyUsed1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: false,
    question: "taxPayerRealEstate_NumberOfRentalDays1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const spouse = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Advertising",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_CleaningAndMaintenance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Commissions",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Insurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Professional",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_LegalAndFees",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_ManagementFees",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_MortgageInterestPaidToBanks",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_OtherInterest",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Repairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_SuppliesHardwareEtc",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_TaxesProperty",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_TaxesPayroll",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Utilities",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_Wages",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_CondoOrHomeownerAssociationDues",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstateExpenses_ForShortTermRentals",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_OwnAnyMoreRealEstate",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_AddressOrDescription1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_Type1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_RentalIncome1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_PercentOwnership1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_IsVocationHome1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_NumberOfDaysPersonallyUsed1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.realEstateRental,
    forSpouse: true,
    question: "spouseRealEstate_NumberOfRentalDays1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons: IRadioGroupItem[] = [
  {
    label: i18n.t("organizer.individual.income.step6.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.individual.income.step6.no"),
    value: false,
  },
];

export const selectType: ISelectProps[] = [
  {
    label: "Single Family Residence",
    value: 1,
  },
  {
    label: "Multi Family Residence",
    value: 2,
  },
  {
    label: "Commercial",
    value: 3,
  },
  {
    label: "Vacation/short term rental",
    value: 4,
  },
];

export const taxPayerDynamic = [
  "taxPayerRealEstate_AddressOrDescription",
  "taxPayerRealEstate_Type",
  "taxPayerRealEstate_RentalIncome",
  "taxPayerRealEstate_ProvideAny1099ks",
  "taxPayerRealEstate_PercentOwnership",
  "taxPayerRealEstate_IsVocationHome",
  "taxPayerRealEstate_NumberOfDaysPersonallyUsed",
  "taxPayerRealEstate_NumberOfRentalDays",
];

export const taxPayerStatic = [
  "taxPayerRealEstateExpenses_Advertising",
  "taxPayerRealEstateExpenses_CleaningAndMaintenance",
  "taxPayerRealEstateExpenses_Commissions",
  "taxPayerRealEstateExpenses_Insurance",
  "taxPayerRealEstateExpenses_Professional",
  "taxPayerRealEstateExpenses_LegalAndFees",
  "taxPayerRealEstateExpenses_ManagementFees",
  "taxPayerRealEstateExpenses_MortgageInterestPaidToBanks",
  "taxPayerRealEstateExpenses_OtherInterest",
  "taxPayerRealEstateExpenses_SuppliesHardwareEtc",
  "taxPayerRealEstateExpenses_Repairs",
  "taxPayerRealEstateExpenses_TaxesProperty",
  "taxPayerRealEstateExpenses_TaxesPayroll",
  "taxPayerRealEstateExpenses_Utilities",
  "taxPayerRealEstateExpenses_Wages",
  "taxPayerRealEstateExpenses_CondoOrHomeownerAssociationDues",
  "taxPayerRealEstateExpenses_ForShortTermRentals",
];

export const spouseDynamic = [
  "spouseRealEstate_AddressOrDescription",
  "spouseRealEstate_RentalIncome",
  "spouseRealEstate_ProvideAny1099ks",
  "spouseRealEstate_PercentOwnership",
  "spouseRealEstate_IsVocationHome",
  "spouseRealEstate_RentalIncome",
];

export const spouseStatic = [
  "spouseRealEstateExpenses_Advertising",
  "spouseRealEstateExpenses_CleaningAndMaintenance",
  "spouseRealEstateExpenses_Commissions",
  "spouseRealEstateExpenses_Insurance",
  "spouseRealEstateExpenses_Professional",
  "spouseRealEstateExpenses_LegalAndFees",
  "spouseRealEstateExpenses_ManagementFees",
  "spouseRealEstateExpenses_MortgageInterestPaidToBanks",
  "spouseRealEstateExpenses_OtherInterest",
  "spouseRealEstateExpenses_SuppliesHardwareEtc",
  "spouseRealEstateExpenses_Repairs",
  "spouseRealEstateExpenses_TaxesProperty",
  "spouseRealEstateExpenses_TaxesPayroll",
  "spouseRealEstateExpenses_Utilities",
  "spouseRealEstateExpenses_Wages",
  "spouseRealEstateExpenses_CondoOrHomeownerAssociationDues",
  "spouseRealEstateExpenses_ForShortTermRentals",
];

export const DATA_KEY = [
  "taxPayerRealEstateExpenses_Advertising",
  "taxPayerRealEstateExpenses_CleaningAndMaintenance",
  "taxPayerRealEstateExpenses_Commissions",
  "taxPayerRealEstateExpenses_Insurance",
  "taxPayerRealEstateExpenses_Professional",
  "taxPayerRealEstateExpenses_LegalAndFees",
  "taxPayerRealEstateExpenses_ManagementFees",
  "taxPayerRealEstateExpenses_MortgageInterestPaidToBanks",
  "taxPayerRealEstateExpenses_OtherInterest",
  "taxPayerRealEstateExpenses_Repairs",
  "taxPayerRealEstateExpenses_SuppliesHardwareEtc",
  "taxPayerRealEstateExpenses_TaxesProperty",
  "taxPayerRealEstateExpenses_TaxesPayroll",
  "taxPayerRealEstateExpenses_Utilities",
  "taxPayerRealEstateExpenses_Wages",
  "taxPayerRealEstateExpenses_CondoOrHomeownerAssociationDues",
  "taxPayerRealEstateExpenses_ForShortTermRentals",
  "taxPayerRealEstate_OwnAnyMoreRealEstate",
  "taxPayerRealEstate_AddressOrDescription1",
  "taxPayerRealEstate_Type1",
  "taxPayerRealEstate_RentalIncome1",
  "taxPayerRealEstate_PercentOwnership1",
  "taxPayerRealEstate_IsVocationHome1",
  "taxPayerRealEstate_NumberOfDaysPersonallyUsed1",
  "taxPayerRealEstate_NumberOfRentalDays1",
  "spouseRealEstate_AddressOrDescription",
  "spouseRealEstate_RentalIncome",
  "spouseRealEstate_PercentOwnership",
  "spouseRealEstate_IsVocationHome",
  "spouseRealEstate_RentalIncome",
  "spouseRealEstateExpenses_Advertising",
  "spouseRealEstateExpenses_CleaningAndMaintenance",
  "spouseRealEstateExpenses_Commissions",
  "spouseRealEstateExpenses_Insurance",
  "spouseRealEstateExpenses_Professional",
  "spouseRealEstateExpenses_LegalAndFees",
  "spouseRealEstateExpenses_ManagementFees",
  "spouseRealEstateExpenses_MortgageInterestPaidToBanks",
  "spouseRealEstateExpenses_OtherInterest",
  "spouseRealEstateExpenses_SuppliesHardwareEtc",
  "spouseRealEstateExpenses_Repairs",
  "spouseRealEstateExpenses_TaxesProperty",
  "spouseRealEstateExpenses_TaxesPayroll",
  "spouseRealEstateExpenses_Utilities",
  "spouseRealEstateExpenses_Wages",
  "spouseRealEstateExpenses_CondoOrHomeownerAssociationDues",
  "spouseRealEstateExpenses_ForShortTermRentals",
];
