import i18n from "../../../../../../i18n";
import { IRadioGroupItem } from "../../../../../../components/RadioGroup/index.props";
import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../../constants/organizer";

export const dataTaxpayerQuestion = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "hasEducationExpensesForYouOrDependents",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "hasForm1098TFromTheEducationInstitution",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "studentsCountToPay",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  // {
  //   categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
  //   forSpouse: false,
  //   question: "1098_upload_file",
  //   answerTypeId: QUESTION_TYPE_ANSWER.number,
  //   answer: null,
  //   message: "",
  //   reminder: false,
  //   isFile: false,
  //   files: null,
  // },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "studentName1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "studentStatus1",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "isStudentFullTime1",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_PostSecondaryTuitionAfterFourYears1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_PostSecondaryTuitionFirstFourYears1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_EnrollmentFeesAndCourseMaterials1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_JobRelatedTuitionAndFees1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_JobRelatedSeminarFees1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_JobRelatedBooksAndSupplies1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_EducationPlans_TuitionK12thGrade1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_EducationPlans_TuitionPostSecondary1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_EducationPlans_BooksAndSupplies1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.educationExpenses,
    forSpouse: false,
    question: "student_EducationPlans_RoomAndBoard1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons: IRadioGroupItem[] = [
  {
    label: i18n.t("organizer.individual.no_flow.step1.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.individual.no_flow.step1.no"),
    value: false,
  },
];

export const dataStudentStatus = [
  {
    label: "Taxpayer",
    value: 0,
  },
  {
    label: "Spouse",
    value: 1,
  },
  {
    label: "Dependent",
    value: 2,
  },
];

export const DATA_KEY = [
  "hasEducationExpensesForYouOrDependents",
  "hasForm1098TFromTheEducationInstitution",
  "studentsCountToPay",
  // "1098_upload_file",
  "studentName1",
  "studentStatus1",
  "isStudentFullTime1",
  "student_PostSecondaryTuitionAfterFourYears1",
  "student_PostSecondaryTuitionFirstFourYears",
  "student_EnrollmentFeesAndCourseMaterials1",
  "student_JobRelatedTuitionAndFees1",
  "student_JobRelatedSeminarFees1",
  "student_JobRelatedBooksAndSupplies1",
  "student_EducationPlans_TuitionK12thGrade1",
  "student_EducationPlans_TuitionPostSecondary1",
  "student_EducationPlans_BooksAndSupplies1",
  "student_EducationPlans_RoomAndBoard1",
];
