import i18n from "../../../../../i18n";
import { IRadioGroupItem } from "../../../../../components/RadioGroup/index.props";
import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";

export const taxPayer = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayer_HaveHomeOfficeExpenses",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOffice_HaveSelfEmployedBusiness",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOffice_DateOfUseBegan",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOffice_EntireHomeArea",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOffice_OfficeArea",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOffice_BusinessStorage",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_TotalRent",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_TotalInsurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_TotalMaintenance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_TotalUtilities",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_TotalRepairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_TotalManagment",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: false,
    question: "taxPayerHomeOfficeExpenses_AmountPaid",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];

export const spouse = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouse_HaveHomeOfficeExpenses",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOffice_HaveSelfEmployedBusiness",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOffice_DateOfUseBegan",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOffice_EntireHomeArea",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOffice_OfficeArea",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOffice_BusinessStorage",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_TotalRent",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_TotalInsurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_TotalMaintenance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_TotalUtilities",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_TotalRepairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_TotalManagment",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.homeOfficeExpenses,
    forSpouse: true,
    question: "spouseHomeOfficeExpenses_AmountPaid",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];

export const radioButtons: IRadioGroupItem[] = [
  {
    label: i18n.t("organizer.individual.income.step5.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.individual.income.step5.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "taxPayerHomeOfficeExpenses_AmountPaid",
  "taxPayer_HaveHomeOfficeExpenses",
  "taxPayerHomeOffice_HaveSelfEmployedBusiness",
  "taxPayerHomeOffice_DateOfUseBegan",
  "taxPayerHomeOffice_EntireHomeArea",
  "taxPayerHomeOffice_OfficeArea",
  "taxPayerHomeOffice_BusinessStorage",
  "taxPayerHomeOfficeExpenses_TotalRent",
  "taxPayerHomeOfficeExpenses_TotalInsurance",
  "taxPayerHomeOfficeExpenses_TotalMaintenance",
  "taxPayerHomeOfficeExpenses_TotalUtilities",
  "taxPayerHomeOfficeExpenses_TotalRepairs",
  "taxPayerHomeOfficeExpenses_TotalManagment",
  "spouseHomeOfficeExpenses_AmountPaid",
  "spouse_HaveHomeOfficeExpenses",
  "spouseHomeOffice_HaveSelfEmployedBusiness",
  "spouseHomeOffice_DateOfUseBegan",
  "spouseHomeOffice_EntireHomeArea",
  "spouseHomeOffice_OfficeArea",
  "spouseHomeOffice_BusinessStorage",
  "spouseHomeOfficeExpenses_TotalRent",
  "spouseHomeOfficeExpenses_TotalInsurance",
  "spouseHomeOfficeExpenses_TotalMaintenance",
  "spouseHomeOfficeExpenses_TotalUtilities",
  "spouseHomeOfficeExpenses_TotalRepairs",
  "spouseHomeOfficeExpenses_TotalManagment",
];
