import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../constants/organizer";
import i18n from "../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_WasAnyPartnerDisregardedEntity",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_DidAnyForeignOrEntityTreatedAsAPartnership",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_DidOwnDirectly20OrMore",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_WasThereDistributionOfPropertyInterestBySale",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_IsPubliclyTradedPartnership",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_Representative_Name",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_Representative_TaxIdNumber",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_Representative_Address",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_Representative_Phone",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question:
      "partnership_DidElectToDeferTheEmployers2020PayrollTaxTo2021And2022Years",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_WasTheOperationFullyOrPartiallyCurtailed",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_DidReceivePaycheckProtectionProgramLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.questionsRelatedToAllCorporations,
    forSpouse: false,
    question: "partnership_DidReceivePaycheckProtectionProgramLoan_Details",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.business.step8.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.business.step8.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "partnership_WasAnyPartnerDisregardedEntity",
  "partnership_DidAnyForeignOrEntityTreatedAsAPartnership",
  "partnership_DidOwnDirectly20OrMore",
  "partnership_WasThereDistributionOfPropertyInterestBySale",
  "partnership_IsPubliclyTradedPartnership",
  "partnership_Representative_Name",
  "partnership_Representative_TaxIdNumber",
  "partnership_Representative_Address",
  "partnership_Representative_Phone",
  "partnership_DidElectToDeferTheEmployers2020PayrollTaxTo2021And2022Years",
  "partnership_WasTheOperationFullyOrPartiallyCurtailed",
  "partnership_DidReceivePaycheckProtectionProgramLoan",
  "partnership_DidReceivePaycheckProtectionProgramLoan_Details",
];
