import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../constants/organizer";
import i18n from "../../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_RealEstatePrimaryResidence_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_RealEstatePrimaryResidence_Date",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_RealEstate2ndHome_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_RealEstate2ndHome_Date",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_RealEstateInvestmentProperty_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_RealEstateInvestmentProperty_Date",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_PersonalPropertyTax_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_PersonalPropertyTax_Date",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_SalesTaxReceipted_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_SalesTaxReceipted_Date",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_SalesTaxCarsBoatsHome_Amount",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_SalesTaxCarsBoatsHome_Date",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_VehicleLicenseFees_Amount1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxesPaid,
    forSpouse: false,
    question: "taxesPaid_VehicleLicenseFees_Date1",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.deductions.step3.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.deductions.step3.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "taxesPaid_RealEstatePrimaryResidence_Amount",
  "taxesPaid_RealEstatePrimaryResidence_Date",
  "taxesPaid_RealEstate2ndHome_Amount",
  "taxesPaid_RealEstate2ndHome_Date",
  "taxesPaid_RealEstateInvestmentProperty_Amount",
  "taxesPaid_RealEstateInvestmentProperty_Date",
  "taxesPaid_PersonalPropertyTax_Amount",
  "taxesPaid_PersonalPropertyTax_Date",
  "taxesPaid_SalesTaxReceipted_Amount",
  "taxesPaid_SalesTaxReceipted_Date",
  "taxesPaid_SalesTaxCarsBoatsHome_Amount",
  "taxesPaid_SalesTaxCarsBoatsHome_Date",
  "taxesPaid_VehicleLicenseFees_Amount",
  "taxesPaid_VehicleLicenseFees_Date",
];
