import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../../../constants/organizer";

export const dataTaxpayerQuestion = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerImagesOfDriversLicense",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerDontHaveDriversLicense",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerAlternateFormOfIDVerification",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerHaveDriversLicenseButCanNotProvideImage",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerImagesOfDriversLicense",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerDriversLicenseIssuedDate",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerDriversLicenseExpiresDate",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: false,
    question: "taxPayerDriversLicenseState",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseImagesOfDriversLicense_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.file,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseDontHaveDriversLicense_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseAlternateFormOfIDVerification_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseHaveDriversLicenseButCanNotProvideImage_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseDriversLicense_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseDriversLicenseState_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.number,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseDriversLicenseIssuedDate_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.taxpayerInformation2,
    forSpouse: true,
    question: "spouseDriversLicenseExpiresDate_NoFlow",
    answerTypeId: QUESTION_TYPE_ANSWER.date,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];

export const TAX_PAYER_NAMES_DRIVER_LICENSE = {
  imageDriversLicense: "taxPayerImagesOfDriversLicense",
  hasDriversLicense: "taxPayerDontHaveDriversLicense",
  taxPayerHaveDriversLicenseButCanNotProvideImage:
    "taxPayerHaveDriversLicenseButCanNotProvideImage",
  idVerification: "taxPayerAlternateFormOfIDVerification",
  driversLicenseNumber: "taxPayerImagesOfDriversLicense",
  state: "taxPayerDriversLicenseState",
  issuedDate: "taxPayerDriversLicenseIssuedDate",
  expires: "taxPayerDriversLicenseExpiresDate",
};

export const SPOUSE_NAMES_DRIVER_LICENSE = {
  imageDriversLicense: "spouseImagesOfDriversLicense_NoFlow",
  hasDriversLicense: "spouseDontHaveDriversLicense_NoFlow",
  spouseHaveDriversLicenseButCanNotProvideImage:
    "spouseHaveDriversLicenseButCanNotProvideImage_NoFlow",
  idVerification: "spouseAlternateFormOfIDVerification_NoFlow",
  driversLicenseNumber: "spouseAlternateFormOfIDVerification_NoFlow",
  state: "spouseDriversLicenseState_NoFlow",
  issuedDate: "spouseDriversLicenseIssuedDate_NoFlow",
  expires: "spouseDriversLicenseExpiresDate_NoFlow",
};

export const DATA_KEY = [
  "taxPayerImagesOfDriversLicense",
  "taxPayerDontHaveDriversLicense",
  "taxPayerDriversLicenseState",
  "taxPayerAlternateFormOfIDVerification",
  "taxPayerDriversLicenseIssuedDate",
  "taxPayerDriversLicenseExpiresDate",
  "spouseImagesOfDriversLicense_NoFlow",
  "spouseDontHaveDriversLicense_NoFlow",
  "spouseDriversLicenseState_NoFlow",
  "spouseAlternateFormOfIDVerification_NoFlow",
  "spouseDriversLicenseIssuedDate_NoFlow",
  "spouseDriversLicenseExpiresDate_NoFlow",
];
