import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../constants/organizer";
import i18n from "../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question:
      "additionalInfo_HaveWrittenAccountingProcedureHowExpensesAreTreated",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question:
      "additionalInfo_HaveAuthorityOverFinancialAccountInForeignCountry",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_HaveAnyDebtThatWasCancelled",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_WasThisPPPLoan",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_HaveForeignBankAccounts",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question:
      "additionalInfo_WasAnyChangeInDeterminingQuantitiesCostValuations",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_HavePreviouslyFiledForeignBankAccountReport",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_HaveIRCSec263AApplied",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_HaveAnyForeignPartnersOrShareholders",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidPayAnyTaxesToForeignGovernment",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidCorporationHave80OrMoreChangeInOwnership",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidPayAnyExpensesToMakeBusinessAccessible",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidPayAnyFICAOnEmployeeWages",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidIncurAnyResearchAndExperimentalExpenditures",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DoesOwnAnyResidentialRentalBuildings",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidEmploy25OrFewerEquivalentFullTimeEmployees",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question:
      "additionalInfo_DidIncurStartUpExpensesForSmallEmployerPensionPlan",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DoesProvideChildCareFacilitiesOrServices",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidPurchaseQualifiePlugInElectricVehicle",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_DidEmploy50OrMoreEquivalentFullTimeEmployees",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_HasFiledOrRequiredToFile8918Form",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question:
      "additionalInfo_Since2017DidForeignCorporationAcquireAllPropertiesOfTheBusiness",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.additionalInformation,
    forSpouse: false,
    question: "additionalInfo_ListAnyOtherBusinessCreditMayQualifyFor1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.business.step7.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.business.step7.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "additionalInfo_HaveWrittenAccountingProcedureHowExpensesAreTreated",
  "additionalInfo_HaveAuthorityOverFinancialAccountInForeignCountry",
  "additionalInfo_HaveAnyDebtThatWasCancelled",
  "additionalInfo_WasThisPPPLoan",
  "additionalInfo_HaveForeignBankAccounts",
  "additionalInfo_WasAnyChangeInDeterminingQuantitiesCostValuations",
  "additionalInfo_HavePreviouslyFiledForeignBankAccountReport",
  "additionalInfo_HaveIRCSec263AApplied",
  "additionalInfo_HaveAnyForeignPartnersOrShareholders",
  "additionalInfo_DidPayAnyTaxesToForeignGovernment",
  "additionalInfo_DidCorporationHave80OrMoreChangeInOwnership",
  "additionalInfo_DidPayAnyExpensesToMakeBusinessAccessible",
  "additionalInfo_DidPayAnyFICAOnEmployeeWages",
  "additionalInfo_DidIncurAnyResearchAndExperimentalExpenditures",
  "additionalInfo_DoesOwnAnyResidentialRentalBuildings",
  "additionalInfo_DidEmploy25OrFewerEquivalentFullTimeEmployees",
  "additionalInfo_DidIncurStartUpExpensesForSmallEmployerPensionPlan",
  "additionalInfo_DoesProvideChildCareFacilitiesOrServices",
  "additionalInfo_DidPurchaseQualifiePlugInElectricVehicle",
  "additionalInfo_DidEmploy50OrMoreEquivalentFullTimeEmployees",
  "additionalInfo_HasFiledOrRequiredToFile8918Form",
  "additionalInfo_Since2017DidForeignCorporationAcquireAllPropertiesOfTheBusiness",
  "additionalInfo_ListAnyOtherBusinessCreditMayQualifyFor",
];

export const STATIC_DATA = [
  "additionalInfo_HaveWrittenAccountingProcedureHowExpensesAreTreated",
  "additionalInfo_HaveAuthorityOverFinancialAccountInForeignCountry",
  "additionalInfo_HaveAnyDebtThatWasCancelled",
  "additionalInfo_WasThisPPPLoan",
  "additionalInfo_HaveForeignBankAccounts",
  "additionalInfo_WasAnyChangeInDeterminingQuantitiesCostValuations",
  "additionalInfo_HavePreviouslyFiledForeignBankAccountReport",
  "additionalInfo_HaveIRCSec263AApplied",
  "additionalInfo_HaveAnyForeignPartnersOrShareholders",
  "additionalInfo_DidPayAnyTaxesToForeignGovernment",
  "additionalInfo_DidCorporationHave80OrMoreChangeInOwnership",
  "additionalInfo_DidPayAnyExpensesToMakeBusinessAccessible",
  "additionalInfo_DidPayAnyFICAOnEmployeeWages",
  "additionalInfo_DidIncurAnyResearchAndExperimentalExpenditures",
  "additionalInfo_DoesOwnAnyResidentialRentalBuildings",
  "additionalInfo_DidEmploy25OrFewerEquivalentFullTimeEmployees",
  "additionalInfo_DidIncurStartUpExpensesForSmallEmployerPensionPlan",
  "additionalInfo_DoesProvideChildCareFacilitiesOrServices",
  "additionalInfo_DidPurchaseQualifiePlugInElectricVehicle",
  "additionalInfo_DidEmploy50OrMoreEquivalentFullTimeEmployees",
  "additionalInfo_HasFiledOrRequiredToFile8918Form",
  "additionalInfo_Since2017DidForeignCorporationAcquireAllPropertiesOfTheBusiness",
];
