import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../constants/organizer";
import i18n from "../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Advertising",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_AutomobileExpenses",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_BadDebts",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_BusinessMeals",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_AmountOfTotalMealsNOTProvidedByRestaurants",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_CommissionsAndFees",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_ContractLabor",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_DuesAndPublications",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_EmployeeBenefitPlans",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_EmployeeHealthCarePlans",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Entertainment",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Equipment200OrLessPerItem",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Freight",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_EquipmentMoreThan200PerItem",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Gifts",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Insurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_InterestMortgage",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_InterestOther",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_InternetService",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_LeaseImprovements",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_LegalProfessional",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Licenses",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_OfficeExpense",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_PensionPlanFees",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_RentEquipment",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_RentOther",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Repairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Supplies",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_TaxesPayroll",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_TaxesSales",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_TaxesProperty",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Telephone",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Utilities",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_W2Wages",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Other_Description1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.expenses,
    forSpouse: false,
    question: "expenses_Other_Amount1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: true,
    files: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.business.step5.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.business.step5.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "expenses_Advertising",
  "expenses_AutomobileExpenses",
  "expenses_BadDebts",
  "expenses_BusinessMeals",
  "expenses_AmountOfTotalMealsNOTProvidedByRestaurants",
  "expenses_CommissionsAndFees",
  "expenses_ContractLabor",
  "expenses_DuesAndPublications",
  "expenses_EmployeeBenefitPlans",
  "expenses_EmployeeHealthCarePlans",
  "expenses_Entertainment",
  "expenses_Equipment200OrLessPerItem",
  "expenses_Freight",
  "expenses_EquipmentMoreThan200PerItem",
  "expenses_Gifts",
  "expenses_Insurance",
  "expenses_InterestMortgage",
  "expenses_InterestOther",
  "expenses_InternetService",
  "expenses_LeaseImprovements",
  "expenses_LegalProfessional",
  "expenses_Licenses",
  "expenses_OfficeExpense",
  "expenses_PensionPlanFees",
  "expenses_RentEquipment",
  "expenses_RentOther",
  "expenses_Repairs",
  "expenses_Supplies",
  "expenses_TaxesPayroll",
  "expenses_TaxesSales",
  "expenses_TaxesProperty",
  "expenses_Telephone",
  "expenses_Utilities",
  "expenses_W2Wages",
  "expenses_Other_Description",
  "expenses_Other_Amount",
];
