import {
  QUESTION_TYPE_ANSWER,
  ORGANIZER_CATEGORY_ID,
} from "../../../../constants/organizer";
import i18n from "../../../../i18n";

export const data = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "income_GrossReceiptsAndSales",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "income_ReturnsAndAllowances",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "income_CostOfGoodsSold",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "income_GrossProfit",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "income_Description1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "income_Amount1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "costOfGoodsSold_InventoryAtBeginingOfYear",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "costOfGoodsSold_Purchases",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "costOfGoodsSold_CostOfLabor",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "costOfGoodsSold_InventoryAtTheEndOfTheYear",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "costOfGoodsSold_Description1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.incomeAndCostOfGoodsSold,
    forSpouse: false,
    question: "costOfGoodsSold_Amount1",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    files: null,
  },
];

export const radioButtons = [
  {
    label: i18n.t("organizer.business.step5.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.business.step5.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "income_GrossReceiptsAndSales",
  "income_ReturnsAndAllowances",
  "income_CostOfGoodsSold",
  "income_GrossProfit",
  "income_Description",
  "income_Amount",
  "costOfGoodsSold_InventoryAtBeginingOfYear",
  "costOfGoodsSold_Purchases",
  "costOfGoodsSold_CostOfLabor",
  "costOfGoodsSold_InventoryAtTheEndOfTheYear",
  "costOfGoodsSold_Description",
  "costOfGoodsSold_Amount",
];
