import i18n from "../../../../../i18n";
import { IRadioGroupItem } from "../../../../../components/RadioGroup/index.props";
import { ORGANIZER_CATEGORY_ID } from "../../../../../constants/organizer";
import { QUESTION_TYPE_ANSWER } from "../../../../../constants/settings";

export const taxPayer = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_HaveVehicleExpensesFromBusinessOrRealEstate",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_HaveVehicleOperatingExpense",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "businessMilesTableInfo",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "vehicleOperatingAndExpensesTableInfo",
    answerTypeId: QUESTION_TYPE_ANSWER.json,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_VehicleMake",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    question: "taxPayer_VehicleModel",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    // sting need change date
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_VehicleYear",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_VehicleAvailableForPersonalUse",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_AnotherVehicleAvailableForPersonalUse",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_HaveWrittenEvidenceToSupportDeduction",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_ParkingExpensesAndTolls",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayer_TotalMilesDrivenThisYear",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_Fuel",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_MaintnanceTiresBatteriesRepairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_Insurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_Licenses",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_LeasePayments",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_LoanInterest",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_Taxes",
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: false,
    question: "taxPayerVehiclExpense_WashAndWax",
    answerTypeId: QUESTION_TYPE_ANSWER.json,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];



export const spouse = [
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_HaveVehicleExpensesFromBusinessOrRealEstate",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_HaveVehicleOperatingExpense",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_VehicleMake",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_VehicleModel",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    // change string to date
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    question: "spouse_VehicleYear",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_VehicleAvailableForPersonalUse",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_AnotherVehicleAvailableForPersonalUse",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_HaveWrittenEvidenceToSupportDeduction",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouse_ParkingExpensesAndTolls",
    answerTypeId: QUESTION_TYPE_ANSWER.boolean,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    question: "spouse_TotalMilesDrivenThisYear",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_Fuel",
    answerTypeId: QUESTION_TYPE_ANSWER.json,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_MaintnanceTiresBatteriesRepairs",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_Insurance",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_Licenses",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_LeasePayments",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_LoanInterest",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_Taxes",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
  {
    categoryId: ORGANIZER_CATEGORY_ID.vehicleOperatingExpenses,
    forSpouse: true,
    question: "spouseVehiclExpense_WashAndWax",
    answerTypeId: QUESTION_TYPE_ANSWER.string,
    answer: null,
    message: "",
    reminder: false,
    isFile: false,
    file: null,
  },
];

export const businessMiles = [
  {
    key: 1,
    name: i18n.t("organizer.individual.income.step4.filed_name1"),
    dataKey: "rental",
    you: "",
    spouse: "",
  },
  {
    key: 2,
    name: i18n.t("organizer.individual.income.step4.filed_name2"),
    dataKey: "employedBusiness",
    you: "",
    spouse: "",
  },
];

export const vehicle = [
  {
    key: 1,
    name: i18n.t("organizer.individual.income.step4.filed_name3"),
    dataKey: "vehiclExpense_Fuel",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 2,
    name: i18n.t("organizer.individual.income.step4.filed_name4"),
    dataKey: "vehiclExpense_MaintnanceTiresBatteriesRepairs",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 3,
    name: i18n.t("organizer.individual.income.step4.filed_name5"),
    dataKey: "vehiclExpense_Insurance",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 4,
    name: i18n.t("organizer.individual.income.step4.filed_name6"),
    dataKey: "vehiclExpense_Licenses",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 5,
    name: i18n.t("organizer.individual.income.step4.filed_name7"),
    dataKey: "vehiclExpense_LeasePayments",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 6,
    name: i18n.t("organizer.individual.income.step4.filed_name8"),
    dataKey: "vehiclExpense_LoanInterest",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 7,
    name: i18n.t("organizer.individual.income.step4.filed_name9"),
    dataKey: "vehiclExpense_Taxes",
    youVehicle: "",
    spouseVehicle: "",
  },
  {
    key: 8,
    name: i18n.t("organizer.individual.income.step4.filed_name10"),
    dataKey: "vehiclExpense_WashAndWax",
    youVehicle: "",
    spouseVehicle: "",
  },
];

export const radioButtons: IRadioGroupItem[] = [
  {
    label: i18n.t("organizer.individual.income.step5.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.individual.income.step5.no"),
    value: false,
  },
];

export const DATA_KEY = [
  "taxPayer_HaveVehicleExpensesFromBusinessOrRealEstate",
  "taxPayer_HaveVehicleOperatingExpense",
  "businessMilesTableInfo",
  "vehicleOperatingAndExpensesTableInfo",
  "taxPayer_VehicleMake",
  "taxPayer_VehicleModel",
  "taxPayer_VehicleYear",
  "taxPayer_VehicleAvailableForPersonalUse",
  "taxPayer_AnotherVehicleAvailableForPersonalUse",
  "taxPayer_HaveWrittenEvidenceToSupportDeduction",
  "taxPayer_ParkingExpensesAndTolls",
  "taxPayer_TotalMilesDrivenThisYear",
  "taxPayerVehiclExpense_Fuel",
  "taxPayerVehiclExpense_MaintnanceTiresBatteriesRepairs",
  "taxPayerVehiclExpense_Insurance",
  "taxPayerVehiclExpense_Licenses",
  "taxPayerVehiclExpense_LeasePayments",
  "taxPayerVehiclExpense_LoanInterest",
  "taxPayerVehiclExpense_Taxes",
  "taxPayerVehiclExpense_WashAndWax",
  "spouse_HaveVehicleExpensesFromBusinessOrRealEstate",
  "spouse_HaveVehicleOperatingExpense",
  "spouse_VehicleMake",
  "spouse_VehicleModel",
  "spouse_VehicleYear",
  "spouse_VehicleAvailableForPersonalUse",
  "spouse_AnotherVehicleAvailableForPersonalUse",
  "spouse_HaveWrittenEvidenceToSupportDeduction",
  "spouse_ParkingExpensesAndTolls",
  "spouse_TotalMilesDrivenThisYear",
  "spouseVehiclExpense_Fuel",
  "spouseVehiclExpense_MaintnanceTiresBatteriesRepairs",
  "spouseVehiclExpense_Insurance",
  "spouseVehiclExpense_Licenses",
  "spouseVehiclExpense_LeasePayments",
  "spouseVehiclExpense_LoanInterest",
  "spouseVehiclExpense_Taxes",
  "spouseVehiclExpense_WashAndWax",
];
export const dataRadio = [
  {
    label: i18n.t("organizer.individual.income.step2.yes"),
    value: true,
  },
  {
    label: i18n.t("organizer.individual.income.step2.no"),
    value: false,
  },
];